name: WebdriverIO Tests on BrowserStack

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    # Reinstall Allure CLI globally (if not already installed in the environment)
    - name: Install Allure CLI
      run: |
        ALLURE_VERSION=2.20.1
        curl -o allure-$ALLURE_VERSION.tgz -L https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
        tar -zxvf allure-$ALLURE_VERSION.tgz
        sudo mv allure-$ALLURE_VERSION /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
      shell: /usr/bin/bash -e {0}

    # Run WebdriverIO tests on BrowserStack
    - name: Run WebdriverIO tests on BrowserStack
      run: npm run test:android
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        BROWSERSTACK_APP_ID: ${{ secrets.BROWSERSTACK_APP_ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
      continue-on-error: true

    # Generate Allure Report
    - name: Generate Allure Report
      if: always()
      run: npm run allure:generate

    # Upload WebdriverIO test results as artifact (optional)
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: webdriverio-test-results
        path: allure-results/

    # Get Allure history from the gh-pages branch to retain trends
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # Use Allure Report Action from Marketplace to handle report generation and history
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: gh-pages/allure-history
        keep_reports: 20

    # Deploy Allure report with history to GitHub Pages
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: gh-pages/allure-history
